# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('learn_more', models.URLField()),
                ('donate_url', models.URLField()),
                ('volunteer_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('match', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchRel',
            fields=[
                ('matchrel_id', models.AutoField(primary_key=True, serialize=False)),
                ('match_id', models.IntegerField()),
                ('org_id', models.IntegerField()),
                ('action_id', models.IntegerField()),
                ('approved', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('org_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
