# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='text',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matchrel',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
