# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20160408_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchrel',
            name='action_id',
        ),
        migrations.RemoveField(
            model_name='matchrel',
            name='match_id',
        ),
        migrations.RemoveField(
            model_name='matchrel',
            name='org_id',
        ),
        migrations.AddField(
            model_name='matchrel',
            name='action',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='src.Action'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchrel',
            name='match',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='src.Match'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchrel',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='src.Organization'),
            preserve_default=False,
        ),
    ]
