# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_auto_20160409_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='src.Organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='donate_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='learn_more',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='volunteer_url',
            field=models.URLField(blank=True),
        ),
    ]
