# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_remove_matchrel_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='rating',
            field=models.IntegerField(choices=[(-1, 'No rating available'), (0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=-1),
        ),
    ]
